import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiFillGithub,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import logo from "../public/logobg.png";

import Link from "next/link";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Hüseyin Battal | Full Stack Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl"><Image height={50} width={50} src={logo} /></h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a target="blank"
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://media-exp1.licdn.com/dms/document/C4D1FAQFsPVnt4owVxQ/feedshare-document-pdf-analyzed/0/1669651386044?e=1670457600&v=beta&t=Sf1DI0t3DQBfI7qsyfV-4fpHtqGoIB-Pn191zkinU2U"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Hüseyin Battal
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              React.JS Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
            +1 year experienced in IT and a software developer. I have been focusing on MERN Stack technologies for the last year. I'm developing full-stack projects with React.js and Node.js
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <div className="cursor-pointer hover:text-blue-400"><Link href="https://twitter.com/hsyn_bttl"><a target="blank"><AiFillTwitterCircle /></a></Link></div>
              <div className="cursor-pointer hover:text-blue-500"><Link href="https://www.linkedin.com/in/huseyinbattal42/"><a target="blank"><AiFillLinkedin /></a></Link></div>
              <div className="cursor-pointer hover:text-purple-800"><Link href="https://github.com/huseyinbattal"><a target="blank"><AiFillGithub /></a></Link></div>
              
              
            </div>
          
          </div>
        </section>
        <hr/>
        <section className="py-10">
        <h1 className="text-4xl py-1 dark:text-white text-center font-mono text-blue-900 ">Portfolio</h1>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Link href="https://github.com/huseyinbattal/Movie-App-with-React-Redux" ><a target="blank"><h1 className="text-red-500 font-bold text-center hover:cursor-pointer hover:text-blue-700 dark:text-white">Movie App</h1></a></Link>
              <Image
                className="rounded-lg object-fit"
                width={200}
                height={200}
                layout="responsive"
                src={web1}
              />
            </div>
            <div className="basis-1/3 flex-1">
            <Link href="https://github.com/huseyinbattal/book-it" ><a target="blank"><h1 className="text-red-500 font-bold text-center hover:cursor-pointer hover:text-blue-700 dark:text-white">Book IT</h1></a></Link>
              <Image
                className="rounded-lg object-fit"
                width={200}
                height={200}
                layout="responsive"
                src={web2}
              />
            </div>
            <div className="basis-1/3 flex-1">
            <Link href="https://github.com/huseyinbattal/magic-form" ><a target="blank"><h1 className="text-red-500 font-bold text-center hover:cursor-pointer hover:text-blue-700 dark:text-white">Magic Form</h1></a></Link>
              <Image
                className="rounded-lg object-fit"
                width={200}
                height={200}
                layout="responsive"
                src={web3}
              />
            </div>
            <div className="basis-1/3 flex-1">
            <Link href="https://github.com/huseyinbattal/Live-Chat-App-with-Node.js" ><a target="blank"><h1 className="text-red-500 font-bold text-center hover:cursor-pointer hover:text-blue-700 dark:text-white">Live Chat</h1></a></Link>
              <Image
                className="rounded-lg object-fit"
                width={200}
                height={200}
                layout="responsive"
                src={web4}
              />
            </div>
            <div className="basis-1/3 flex-1">
            <Link href="https://github.com/huseyinbattal/React-Tic-Tac-Toe-Game" ><a target="blank"><h1 className="text-red-500 font-bold text-center hover:cursor-pointer hover:text-blue-700 dark:text-white">XOX</h1></a></Link>
              <Image
                className="rounded-lg object-fit"
                width={200}
                height={200}
                layout="responsive"
                src={web5}
              />
            </div>
            <div className="basis-1/3 flex-1">
            <Link href="https://github.com/huseyinbattal/huseyin-battal-portfolio-site" ><a target="blank"><h1 className="text-red-500 font-bold text-center hover:cursor-pointer hover:text-blue-700 dark:text-white">Personal Website</h1></a></Link>
              <Image
                className="rounded-lg object-fit"
                width={200}
                height={200}
                layout="responsive"
                src={web6}
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
